### PR TITLE
xsd2json: Fix handling of namespaces

### LINKED ISSUE #80: xsd2json: Wrong handling of namespaces
Pull request #69 did not fix #67 in the correct way. The solution was too superficial. The real problem is deeper in the xsd2json code and needs to be fixed with a more thorough change.

The main problem is that the `name` of a definition is treated as a `QName` in xsd2json. But it is really just a local name that is always bound to the target namespace. This subtle difference is important, because all the real `QName`s (`type`, `ref`, etc.) do not care about the target namespace at all. If these have no prefix, they must be bound to whatever namespace is bound to the empty prefix (`xmlns=...`). Even more so, there is a special rule in XML Schema that if the empty prefix is unbound, it defaults to the XML Schema namespace, not the target namespace!

So it is wrong to ever bind targetNS to the empty prefix by any automatism. Instead, definition names need to be resolved by a separate mechanism.

To illustrate the issue, consider the following definition:

```xml
<xs:schema ... xmlns="http://example.com/bar" targetNamespace="http://example.com/foo">
  <xs:element name="Foo" type="date"/>
</xs:schema>
```

Here, `Foo` is bound to the `http://example.com/foo` namespace, while `date` is looked up in the `http://example.com/bar` namespace.

Moreverover, if the `xmlns=...` definition is left out:

```xml
<xs:schema ... targetNamespace="http://example.com/foo">
  <xs:element name="Foo" type="date"/>
</xs:schema>
```

then `Foo` is still bound to the `http://example.com/foo` namespace, while `date` is looked up in the `http://www.w3.org/2001/XMLSchema` namespace.

In neither case `date` is ever looked up in the target namespace.

### PR DESCRIPTION
**Pull request by vog**
This fixes #80.

Note that this pull request depends on #79, as it contains and adjusts unit tests.

### CODE REVIEW

File: xsd/src/schema_manager.js [hunk 1]
```diff
@@ -237,7 +237,9 @@ SchemaManager.prototype.exportNamespaces = function() {
 	var self = this;
 	var namespacePrefixes = {};
 	var prefixUsed = {};
+	this.addNamespacePrefixes(namespacePrefixes, prefixUsed, {'xs': self.xsNS});
```
Comment (vog) [inline xsd/src/schema_manager.js]: Just for clarity: This is a purely "cosmetic" change that happens after all XSD parsing is finished. It affects only the prefixes chosen for the final "schema.namespace" sub structure and nothing else.

This has nothing to do with the bug fixes discussed here, and could have been proposed in a separate pull request.

The only reason I was including it here is because it ensures that most test cases remain stable after the fix. Otherwise, some namespace prefixes of the final result schema would change, leading to not-nice-looking namespace prefixes to the user.

Maybe this is easier demonstrated than explained: Just disable this and the other "addNamespacePrefixes" calls, and compare the generated schemas (for the then-failing test cases). That should increase the clarity.

File: xsd/src/schema_manager.js [hunk 2]
```diff
@@ -237,7 +237,9 @@ SchemaManager.prototype.exportNamespaces = function() {
...
 	this.addNamespacePrefixes(namespacePrefixes, prefixUsed, self.originatingSchema.localNamespaces);
+	this.addNamespacePrefixes(namespacePrefixes, prefixUsed, {'': self.originatingSchema.targetNS});
```
Comment (vog) [inline xsd/src/schema_manager.js]: Please look at my other comment. This change is purely cosmetic for the final result, and has nothing to do with the bugfix.

**Comment by vog** [comment]
@bbpennel Thanks for the additional test cases. I was not aware that xsd2json was supposed to support that special case (schemas without targetNS) already. Obviously I overlooked those demo schemas, I tought I included all of them in #78.

File: xsd/src/schema_manager.js (hunk 1 above)
Comment (vog) [inline xsd/src/schema_manager.js]: Please also have a look at the respective commit messages (emphasis on "in final schema JSON"):

* a861932cb071dd98b61664c6ac70e1780445da25
* 852e112a26b1df11d6c478db58e92c0b9bf7b590

**Comment by vog** [comment]
@bbpennel Would you mind adding the missing demo schemas in full, as test cases? (in addition to the specialized test cases `issue-080-4` and `issue-080-5`)

**Comment by bbpennel** [comment]
I've added tests for the demo schemas and fixed some issues with the other two tests i'd added

**Comment by vog** [comment]
Thanks for fixing a first set of bugs in your test cases. However, there are still problems in the test schemas that we need to fix before we can use them to verify the `xsd2json` tool.

Some schemas do not fully work as intended, i.e. an XML Schema validator interprets those differently from what is stated in the `schema.json` JSON file.

Other schemas are even invalid XML Schema files.

I'll get into more details in my following commits and comments.

**Comment by vog** [comment]
Now that the XSD files are valid, it was possible to add support for empty namespaces as well as Chameleon Inclusion, see commit 71a063deb74e9fb22ce837b6c4c3369cf0ffd5f5.

All test cases are green now.

**Comment by vog** [comment]
However, one minor issue remains (not affecting the test cases): In the hand-written XSD files the declaration `elementFormDefault="qualified"` is missing.

From the result JSON files it is pretty clear that when a targetNamespace is given, all sub elements are meant to be placed into the targetNamespace, not the empty (unqualified) namespace. So `elementFormDefault="qualified"` is required. (Alternatively, all `element` definitions would need `form="qualified"`, which would be a bit cumbersome),

Moreover, `xsd2json` is obviously written with `elementFormDefault="qualified"` in mind, as it makes no difference between top-level and local element definitions. And the other (rarely used) variants for the `form` and `...FormDefault` schema attributes are not supported by `xsd2json` at all, because these attributes are not evaluated anywhere in the program. And this is perfectly okay, but it means that we shouldn't trigger those special cases in our test cases until we actually want to implement those other `form` variants.

So I look the freedom to fix your test cases in that regard and hope this is okay for you, see commit 370b354d744e3eaf17d4b16d280825ab0f60e310.

**Comment by bbpennel** [comment]
Thank you for cleaning those up, @vog, this looks good!
